### ISSUE TITLE
Typos

### ISSUE THREAD

**Issue by klassenjo** [sidequestdev/platform#2]
![image](https://user-images.githubusercontent.com/1273791/180627033-4aa80596-7bfa-4d14-8909-9db22a747b85.png)
![image](https://user-images.githubusercontent.com/1273791/180627237-9d13a518-bd71-442e-952e-ab6fb48b6171.png)

**Comment by jakeklassen** [comment]
closed in 2398eed5f927acf35033c6403c9b8966368ff840 and 24ed92710cf2e5e33fb9fc0c057bc53e0f644d25
